name: cd

on:
  push:
    branches:
      - main
  schedule:
    - cron: '10 9 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: webapp

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci
      - run: npm run generate
        env:
          API_URL: ${{ secrets.API_URL }}
          ANALYTICS_ENABLED: ${{ secrets.ANALYTICS_ENABLED }}
          ANALYTICS_URL: ${{ secrets.ANALYTICS_URL }}
          ANALYTICS_DOMAIN_URL: ${{ secrets.ANALYTICS_DOMAIN_URL }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webapp/dist
          cname: wods.vincenthardouin.dev
